# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

services:

    kolektifapi:
        container_name: kolektifapi
        build: .
        ports:
            - 8080:8080
        image: kolektifapi:latest
        restart: always
        volumes:
            - 'self:/usr/src/app'
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    self: