# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

services:

    kolektifapi:
        container_name: kolektifapi
        build: .
        ports:
            - 1453:1453
        image: kolektifapi:latest
        restart: always
        volumes:
            - self:/usr/src/KolektifAPI
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    self: